app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    schemes:  [https]

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

dimad_fos_user:
    resource: "@DimadUserBundle/Resources/config/routing/security.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"