app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

dimad_fos_user:
    resource: "@DimadUserBundle/Resources/config/routing/security.xml"
